name: pong
on:
  push:
    branches:
    - master
    tags:
    - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v -short -race ./...

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:
        name: tobiasdenzler/pong
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        tag_names: true
